language: node_js
node_js:
  - 12.10.0
cache: npm
deploy:
  provider: heroku
  api_key:
    secure: okzAhHIgoFxu5slvSLZruup5vkdhGtbR/WoBmedIQTwKwQyT44yaqaCdQ1DjyWmT0WUfkLdhusy5fIoKGY5sdorkc8lO9YgHY6f1DzIItDn5klDuaZ1eY0Q3mwO3IWj4Yr4pjZi+9i2CN91UKe7ybn0YnO1E1Bqu12NcZqEpJ4SRTyPJc+9O/VdhUeEPrBVJQMJfquHddvv8pIpdTIxuZM0m2+i3hUJNQaTo9CjSF0Fb9V0RsNq1L9xee4tpddV0QtQn8FTw7ywUX2DPbX0gutuW1qn8JaJ9H45cxDyD9uAsXtMeeWqEJeO7SKRlewUIRLtYz331GWV8yAgjfnE30wPKk7aOZjxjzFpgCD5mBZIuy7IN1TvOLq0ZqEMGED+0FlRXI0yFsDFlDyhngbsBpYb30BV5Q5vvSYv7jK5D+EV5do3qh6vp3WGiB19C3bGxL1ErveMUkDbYEqLlLlhwXyu6ftjrVq0w3jtwpAassPHz0aUoBv4ccCxLi3YfeSpZHhl5ODx9rxm9ehM0R9kXOQGKhMMBVvV6C1hn1OMoGXOxB3EyPfoJTB9yWKVJzrZkGaFZMKBV/w7aCiQeyhQTOLnAl86a8JeS1hNoxD0mZQh/MyyEsfjFhwbBxRq6uGH7W8Rw9TGzzv8dOZskvJFGMAgb5NLUmuv1FDc3ClIYAs8=
  app: powergrid-app
  on:
    repo: MaximumBlueGreen/powergrid-api
    branch: develop
services:
  - postgresql
before_script:
  - psql -c "create database powergrid_travis;" -U postgres
  - knex migrate:latest
script:
  - npm test
  - npm run lint
env:
  - NODE_ENV=test DATABASE_URL=postgres://localhost/powergrid_travis JWT_SECRET=SECRETSANTA
branches:
  only:
    - develop
