language: node_js
node_js:
- 9.3.0
cache: npm
deploy:
  provider: heroku
  api_key:
    secure: PBBq0k6PSQszxTAKoFmfm6POErzv3rLNjauSOxCKctlPc6UVEktXSTXxODO4WMJojPJPFWJEnRD8IF6382wuYg0sNiGPkNLdRnB/qzDX1YChpeyWkoAO3pA6oXRRogc54ropnYY9oHs1FrGLo27GXL2+BaEKDWd1pIztMeIYa3F/VZBdrQ2YGhIaOwuBaVhCtXybEtirsqK8DYcswIxoThjU9jqUv3ZuURK90uJom3CH63jNlb5tKB6P2qXmzD3iMyvBEAvnwoeR6SONUjvA4bbjiLD0OSDWGGmsQxaP/+TSWsPW5ZLnFr50Lh5T4d6E3RgSOO9ARH6/qzNxPXxJpSTFn6DDSS8fVKxOF49gAMZsf2F2SpsJnS2Mx5QEWvfoFYMEVhOkhvlcUbG5NbHMp1nziBzQvJrkbreO07/zqzKhG2GJUCkJOnlpEhxavq2I8CekR5eAceaHm17nnnZo5yvYvZB2jgUZE8jcfG+MaNMNxlR1/tc1dNA/6L4gJBuVdaIRYWTs1VBS0dvLqeM23uv3J7wNdhsZo3ysbDqHhAuC1lmYhNT0oXZg5YFy0OJHwighr5uuPF5SzavOpKW9kM92UfhDUBfkKAQ7dcpID4LavjD8PphqfWZYeGcRHAox5gR8WuClssfDo3YoA1XRaP0fxaIeFHdv+OITxEm/cuo=
  app: powergrid-app
  on:
    repo: MaximumBlueGreen/powergrid-api
    branch: develop
services:
- postgresql
before_script:
- psql -c "create database powergrid_travis;" -U postgres
- knex migrate:latest
script:
- npm test
- npm run lint
env:
- NODE_ENV=test DATABASE_URL=postgres://localhost/powergrid_travis JWT_SECRET=SECRETSANTA
branches:
  only:
  - develop
